### PR TITLE
remove setup.py, add ian as author

### PR DESCRIPTION
**Pull request by tlambert03**

### CODE REVIEW

**Comment by tlambert03** [comment]
ok being added to authors @ianhi ?

**Comment by ianhi** [comment]
> ok being added to authors @ianhi ?

Definitely! thanks :)

**Review by ianhi — CHANGES_REQUESTED** [review]
While I'm down with adding me as an author I'm pretty sure think we can't fully remove setup.py until some future advances in setuptools :(. Removing it now would mean that you can't make an editable install. See  https://github.com/pypa/setuptools/issues/2816 for more details.

**Comment by tlambert03** [comment]
Yep, pip added support for editable installs without setup.py towards the end of last year.  I've been removing setup.py from a few projects with no issues so far.

**Pull request merged**
