### PR TITLE
remove caching

### PR DESCRIPTION
**Pull request by ianhi**
in the hopes that it will fix flaky tests

### CODE REVIEW

**Comment by ianhi** [comment]
this craziness: 
image

**Comment by ianhi** [comment]
and that fixed it I guess? weird

**Comment by tlambert03** [comment]
nice!  gonna rerun a couple times

**Comment by tlambert03** [comment]
and again.  this is the vaguely the kind nonsense I was referring to in that [other discussion about caching](https://github.com/tlambert03/napari-micromanager/pull/89#discussion_r796029183).  I have no idea why this shouldn't work, but lets go with it :)

**Comment by ianhi** [comment]
ok now i'm very confused: after merge all but one passed

https://github.com/tlambert03/pymmcore-plus/runs/5255761770?check_suite_focus=true

**Comment by tlambert03** [comment]
darn! :joy:  was this the same error as before?

**Comment by ianhi** [comment]
what's odd is that the thread object should really never be none there. even if the thread had finished I wouldn't have expected that

**Comment by tlambert03** [comment]
yep. totally confused about that too.  very odd indeed

**Pull request merged**
