### PR TITLE
create docs

### PR DESCRIPTION
**Pull request by ianhi**
Would be nice to also enable autobuild on PRs. Though that depends on how you want to host these @tlambert03. If we want to start with readthedocs then I know it's pretty easy.

Also cc @fdrgsp for more eyes on this.

### CODE REVIEW

**Comment by tlambert03** [comment]
thanks @ianhi!  I'm happy to use readthedocs to keep it easy

**Comment by tlambert03** [comment]
this looks amazeballs at first glance.  will pull and build when I have a moment

**Comment by ianhi** [comment]
If you set up readthedocs you won't even need to build! https://docs.readthedocs.io/en/stable/pull-requests.html

**Comment by tlambert03** [comment]
yep, I do like RTD.  use it for a few projects (https://ome-types.readthedocs.io/en/latest/, https://napari-plugin-engine.readthedocs.io/en/latest/)

**Comment by ianhi** [comment]
one todo here is to publicly expose the Signaller object so that it can be captured by autodoc.

**Comment by ianhi** [comment]
> should add docs/api to .gitignore

Ahh the curse of the unpushed commit.

> I'm not a big fan of sphinx_book_theme. would prefer furo, sphinx-material, or pydata-sphinx

I like those as well, with a preference for that order. 

> lets get rid of sphinx-thebe for now. I don't think we need this to interactive, or at the very least, it will need some work to make it so

indeed. removed

**Comment by tlambert03** [comment]
i think this is a great start, so I'm going to merge.  We can continue to iterate in later PRs

**Review by tlambert03 — APPROVED** [review]

**Pull request merged**
