### PR TITLE
Move remote stuff to subfolder, make pyro5 optional [remote] extra

### PR DESCRIPTION
**Pull request by tlambert03**
the remote functionality brings in a few extra dependencies... so this makes them all optional

### CODE REVIEW

**Review by ianhi — APPROVED** [review]
Looks good

Only question is: Does it make sense keep it at all? Given the known reliability issues (https://github.com/tlambert03/pymmcore-plus/issues/43) I don't think I would recommend anyone use it. The major uses case I think of is from another computer

**Comment by tlambert03** [comment]
> Does it make sense keep it at all? Given the known reliability issues (https://github.com/tlambert03/pymmcore-plus/issues/43) I don't think I would recommend anyone use it.

While I agree that it shouldn't be the default, I'm not yet ready to drop it entirely.  It _is_ a compelling use case if only we could solve #43 (which i still imagine is possible... I see that issue as me just not using pyro 100% correctly).  So, let's punt on whether we fully remove

**Comment by ianhi** [comment]
Is it possilbe to override `__dir__` as well so that if you are for example `shift-tabbing` in a notebook then Remote will still show up? This works in VSCode but not in jupyterlab, or any other jedi based systems I imagine.

**Comment by ianhi** [comment]
Doing this brings back autocomplete for jedi:

```python
dir_ = dir() + ["RemoteMMCore", "server"]
def __dir__():
    return dir_
```

but it also feels somewhat wrong.

**Comment by tlambert03** [comment]
> Doing this brings back autocomplete for jedi:
> but it also feels somewhat wrong.

let's go with

```py
def __dir__():
    return __all__
```

**Comment by ianhi** [comment]
>      let's go with

> def __dir__():
>    return __all__

I tried that as well but then you lose all the normal dunder methods on shift tab :(.

**Comment by tlambert03** [comment]
ah, ok, then:
```python
def __dir__():
    return list(globals()) + ['RemoteMMCore', 'server']
```

**Comment by ianhi** [comment]
Just checked - that works!

**Pull request merged**
