### PR TITLE
Doc follow ups

### PR DESCRIPTION
**Pull request by ianhi**
We should also:

1. Add a link to the github about section
2. Have RTD build on PRs (only @tlambert03 can enable that)

### CODE REVIEW

**Comment by tlambert03** [comment]
it's already up on rtd https://pymmcore-plus.readthedocs.io/en/latest/

**Comment by tlambert03** [comment]
enabled

**Comment by ianhi** [comment]
hmm linkcode works locally but not on readthedocs :/

**Comment by tlambert03** [comment]
> hmm linkcode works locally but not on readthedocs :/

not following... what is link code?

**Comment by ianhi** [comment]
> not following... what is link code?

It's the function in conf.py that makes the [Source] in the api docs:
image

link to github.


also I should say that it's fixed now :)

**Comment by ianhi** [comment]
Previously it was rendering as these broken links: https://github.com/tlambert03/pymmcore-plus/blob/envs/latest/lib/python3.8/site-packages/pymmcore_plus/core/_constants.py#L60-L67

**Pull request merged**
