### PR TITLE
Add automatic micromanager discovery for linux

### PR DESCRIPTION
**Pull request by ianhi**
If you follow the steps in the Docker file for pymmcore (https://github.com/micro-manager/pymmcore/blob/main/Dockerfile)
then you end up with an installation in `/usr/local/lib/micro-manager/`

Also, paths are case senstive on linux hence so search for both capital
and lowercase `m` in the glob.

Finally, added the searched path to the logger if nothing was found in
case people have non-standard install locations.

---

Annoyingly however this won't automatically grab the demo config as the install instructions don't move it to `/usr/local/lib/micro-manager`  so you still need to explicitly locate the path

### CODE REVIEW

**Review by tlambert03 — APPROVED** [review]
awesome thanks!  

are you actually using this on linux out of curiosity?  Or just saw the `NotImplementedError` and filled it in?

**Comment by tlambert03** [comment]
as an aside ... it would be kinda cool if we could get something like that docker runfile into the [installer script](https://github.com/tlambert03/pymmcore-plus/blob/main/pymmcore_plus/install.py) for convenience.

**Comment by ianhi** [comment]
> are you actually using this on linux out of curiosity? Or just saw the NotImplementedError and filled it in?

Yup! My personal computer is linux only so I ran into this pretty much immediately.

**Comment by ianhi** [comment]
> as an aside ... it would be kinda cool if we could get something like that docker runfile into the installer script for convenience.

Indeed. Also maybe a `linux-troubleshooting.md` could be helpful?

**Comment by tlambert03** [comment]
cool.  do you know how many of the device adapters would work on linux?  or mostly just convenient for development? (similar to mac i guess)

**Comment by ianhi** [comment]
I don't know because I haven't really had the opportunity to try (I only really have access to three micrscopes all of which have setups that I'd prefer not accidently undo their working status. Plus mostly they are not primarily in my care). I got this going so I could mess around with this repo.

**Pull request merged**
